If "tabs.tabs_are_windows" is set, "tab-close" should map to "close"
qutebrowser/qutebrowser pull request #5771
Opened 2020-10-06 18:09 UTC by C0DK

The code should be self explainatory, but i'm basically overriding the default behaviour of the `tab_close` of the last tab if `last_close` is set to `ignore`..  One could also create another label that does this more directly. Feedback is welcome.
fixes #5695

I have not been able to run the tests locally.

Also would it be possible to tag the repo or this PR as a hacktober-friendly application? If not that is fine as well - I've primarily wanted to give back to qutebrowser because I've been using it for a long time.

2020-10-11 12:39 UTC, The-Compiler commented
Sorry for the delay! The failing test isn't your fault, it's a flaky test which I tried to stabilize in 093d53f. Can you elaborate on what gave you trouble with running the tests locally? I'd love to try and improve that :slightly_smiling_face: 

I'd like to have a test added for this PR as well, but tests with multiple windows are a bit tricky to do at the moment, so I'll need to experiment a bit - I'll get back to it in the next couple of days!

2020-10-21 15:11 UTC, C0DK commented
@The-Compiler status? :) I am trying to get my hacktoberfest shirt and would love for it to be accepted before end of month haha :D (or add `hacktoberfest-accepted` as a label :P ) Not to be needy

2020-10-21 15:18 UTC, C0DK commented
Ups i never sent my message regarding feedback on tests ^ ^ I can add an issue with that, i guess, but i needed a clear way to install all dependencies. The tests had a lot of dependencies not in requirements. I can see that some repos use a `test_requirements.txt` file, so that might be a way to resolve it :) 

Also just running the source locally was difficult. It had a difficult time finding a valid version of QT - might be a conflict or something with the qutebrowser i have installed. not sure.

2020-10-21 15:33 UTC, The-Compiler commented
Yep, I'll definitely get back to this before the end of the month. :slightly_smiling_face: For now, let me just accept the PR as I can take care of the test and it looks good otherwise.

As for test requirements and getting Qt, all you should need is `tox` and it'll take care of setting up the rest - did you see the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc)?

2020-10-21 15:34 UTC, The-Compiler approved these changes

2020-10-21 17:32 UTC, C0DK commented
> As for test requirements and getting Qt, all you should need is `tox` and it'll take care of setting up the rest - did you see the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc)?

I only skimmed them. Sorry I should have read them more carefully.

2020-10-26 17:24 UTC, The-Compiler requested changes
I just wrote a test for this and then discovered it doesn't actually work :wink:

Did you test it manually? When I do, I end up with an empty window with no tabs in it, because the tab gets removed but the window doesn't actually get closed.

2020-10-27 08:49 UTC, C0DK commented
Ups, thank you :) I wil fix this tomorrow evening.

2020-12-09 18:14 UTC, markstos commented
I wonder if this issue is the cause of some windows that pop up don't close themselves as expected.  For example, a site pops up "Login with Google" in a new window, and the the flow completes successfully, but the pop-up doesn't close itself as expected after login and needs to be manually closed. I suppose I could find a  case that reproduces the issue and then test this patch against it. I'll keep that in mind the next time I run into this.

2020-12-10 14:28 UTC, C0DK commented
I never fixed this - sorry - been very busy with family, studies and work. Won't have time any time soon sadly. Sorry.

2020-12-10 16:51 UTC, markstos commented
I'll try to take a look at this if someone else doesn't get to it first.

2020-12-22 13:32 UTC, The-Compiler commented
I ended up with a slightly different approach (which works properly and closes the window) in 1c9bb926c. Thanks for the contribution anyways, @C0DK!

@markstos I doubt this is related, as this is only specific to the `tabs_are_windows` setting - if you can still reproduce it on master, can you please open a separate issue with more information?

2020-12-22 13:32 UTC, closed without merging