Fix qute-pass crash from wrong cache directory
qutebrowser/qutebrowser pull request #5830
Opened 2020-10-23 17:56 UTC by jtyers

Owing to [this tldextract issue](https://github.com/john-kurkowski/tldextract/issues/209), the `qute-pass` userscript attempts to write cache data to a system directory, causing the script to crash with `PermissionDenied`. This fix tells `tldextract` to cache to `QUTE_DATA_DIR` instead (it creates a `.suffix_cache` file in that directory).

2020-10-23 18:11 UTC, The-Compiler commented
Seems reasonable! cc @bascht @lufte

2020-10-23 18:22 UTC, The-Compiler requested changes
On a second thought, this should use `QUTE_CACHE_DIR` and probably create a subdirectory like `userscripts/tldextract/` or so in there.

2020-10-23 22:30 UTC, jtyers commented
`QUTE_CACHE_DIR` is not set for userscripts, at least for my build:

```
KeyError: 'QUTE_CACHE_DIR'
```

It also doesn't appear in the userscripts docs! Is it implemented on a branch?

2020-10-25 03:21 UTC, Dophin2009 commented
This change will probably also need to be added to the `qute-bitwarden` userscript, which is currently having the same issue.

2020-10-25 14:03 UTC, lufte commented
The discussion [here](https://github.com/john-kurkowski/tldextract/issues/209) seems to indicate they already released a workaround for the issue, so I'm not sure we still need this. They also talk about a permanent fix by using a directory specified by xdg, which would make all instances of tldextract use the same cache file. I guess we need to decide if we prefer to isolate qutebrowser's cache file from the rest or not. If we use tldextract somewhere else in the future, we will need to make sure too that we set the same cache file.

Also where is QUTE_CACHE_DIR defined?

2020-10-25 14:51 UTC, The-Compiler commented
My bad - it indeed looks like `QUTE_CACHE_DIR` isn't available for userscripts.

Given that this is already fixed in tldextract 3.0.2 and the `cache_dir` argument is only compatible with 3.0.0+ which [isn't available widely](https://repology.org/project/python:tldextract/versions), I think this will introduce more issues than it solves. Thus, I'm closing it. Thanks for the contribution anyways!

2020-10-25 14:51 UTC, closed without merging