Qtbot methods changed to snake case,snake case check added
qutebrowser/qutebrowser pull request #6216
Opened 2021-02-26 21:16 UTC by Lembrun

Quickfix to #5864
I guess we could do a script to parse the doc to detect new aliases but I feel for now the above should suffice.

2021-02-26 21:27 UTC, The-Compiler requested changes
I think it should be possible to use a regex like `qtbot\.[a-z]+[A-Z][a-zA-Z]*` to check for this (though I haven't tested)?

Also please integrate the check with the existing code (even if it says "spelling") rather than duplicating it.

2021-02-26 21:40 UTC, Lembrun commented
I did try a regexp of this kind, and replaced everything but I ran into errors in automated test because some methods do not have snake case aliases (keyPress,MousePress,keyClicks.. see [https://pytest-qt.readthedocs.io/en/latest/_modules/pytestqt/qtbot.html](url),)

I'll merge the rest into spelling while waiting for answer

2021-02-26 21:50 UTC, The-Compiler commented
Ah, good point. In that case I'd prefer having a list of those methods which should be ignored, so that when something new gets added to the "hybrid" (snake-case and camel-case API), we don't silently ignore it.

This will need some changes to `misc_checks.py` to have a list of "always allowed" words or so. For now, I'd propose to add a generic regex first (and unify the two functions like mentioned), and we can then take it from there.

2021-02-26 21:55 UTC, The-Compiler commented
Actually... I'm okay with both I guess. Keeping it simple certainly has its benefits as well, though I'm happy to assist if you prefer the more generic approach.

If you want to keep the current one, please merge the related methods into one regex using `wait(Active|Exposed|...)`.

2021-02-27 10:31 UTC, Lembrun commented
Concerning the generic approach I thought about something like this:

`exclude =  Clicks|Click|Press`

`re.compile(r'qtbot\.[a-z]+(?!{})[A-Z].*'.format(exclude))`

Other regexp  for reference : `qtbot\..*[A-Z].+(?=\()(?<!Clicks)(?<!Press)(?<!Click)` (can't simply do |.. because python says negative look .. non fixed)

What do you think ?

2021-03-01 16:55 UTC, The-Compiler requested changes

2021-03-01 16:55 UTC, The-Compiler commented on scripts/dev/misc_checks.py
> +    qtbot_methods = {'keyClick', 'keyClicks', 'mousePress', 'keyPress'}
I think we should have all methods here, even if we don't use them all.

```suggestion
    qtbot_methods = {
        'keyPress',
        'keyRelease',
        'keyClick',
        'keyClicks',
        'keyEvent',
        'mousePress',
        'mouseRelease',
        'mouseClick',
        'mouseMove',
        'mouseDClick',
        'keySequence'
    }
```

2021-03-01 16:55 UTC, The-Compiler commented on scripts/dev/misc_checks.py
> +    excluding = '|'.join(qtbot_methods)
"excluding" is a rather generic name, maybe name it `qtbot_excludes` or so?

2021-03-01 16:55 UTC, The-Compiler commented on scripts/dev/misc_checks.py
> +            re.compile(r'qtbot\.(?!{})[a-z]+[A-Z].*'.format(excluding)),
You can use [f-strings](https://realpython.com/python-f-strings/) instead:

```suggestion
            re.compile(fr'qtbot\.(?!{excluding})[a-z]+[A-Z].*'),
```

2021-03-01 16:55 UTC, The-Compiler commented on scripts/dev/misc_checks.py
> +            "Snake-case available",
```suggestion
            "use snake-case instead",
```

to be consistent with the other messages.

2021-03-01 20:21 UTC, merged

2021-03-01 20:21 UTC, The-Compiler commented
Looks great now, thanks! I also changed the script slightly in 2c8dec9ec so it outputs the matched text instead of the (now rather long) pattern.