Add utils/resources.py
qutebrowser/qutebrowser pull request #6234
Opened 2021-03-07 18:17 UTC by Lembrun

Concerning  #6104

(Btw there there are still some test that are localized to english only ,at some point one test says /nonexistentfile IIRC it happens fairly early in the test suite like 12%-13% ~,

I'd like to give the exact test but my fans are spinning like crazy)

2021-03-08 11:25 UTC, The-Compiler requested changes
Thanks! Looks great overall, I added a couple of comments. Some more generic changes I'd suggest:

- Also split the resource-related tests from `tests/unit/utils/test_utils.py` into a new `test_resources.py` (so there's a rough 1:1 mapping between test files and code files).
- Add `resources.py` and the new tests file to `PERFECT_FILES` in `scripts/dev/check_coverage.py` because it has 100% test coverage.
- Rename internal functions/variables in `resources.py` to remove the `_resource_...` prefix, as it's unneeded when everything is grouped in a `resources.py` now.

2021-03-08 11:25 UTC, The-Compiler commented on qutebrowser/utils/resources.py
> +                    Iterable, TypeVar, TYPE_CHECKING)
Many of those imports are unused - not sure why the linters don't detect that...

2021-03-08 11:25 UTC, The-Compiler commented on qutebrowser/utils/resources.py
> +"""Resources related utilities"""
Nitpick:

```suggestion
"""Resources related utilities."""
```

2021-03-08 11:25 UTC, The-Compiler commented on qutebrowser/utils/resources.py
> +
Nitpick: Remove the blank line

2021-03-08 11:25 UTC, The-Compiler commented on qutebrowser/utils/resources.py
> +def preload_resources() -> None:
I think it'd make sense to rename this to `preload` now that it's namespaced in `resources.py`.

2021-03-08 11:26 UTC, The-Compiler commented
Oh, as for the failing tests - I tried reproducing with a German locale, found two failing tests and fixed them in 45387d18a514103c686be559087420199cb49995.

2021-03-09 20:54 UTC, Lembrun commented
Yeah I was hoping the linters would spare me some more manual work but I guess it can't be helped, the test suite seems to be working on my french locale now nice !

2021-03-11 16:28 UTC, merged

2021-03-11 16:29 UTC, The-Compiler commented
Thanks! Merged with some small adjustments:

- 01b57a33b Merge remote-tracking branch 'origin/pr/6234'
- 822239b12 Make private things private again

(When I mentioned dropping the `resource` prefix, I meant keeping the initial `_` which marks the functions/variables as "private".)

2021-03-11 18:03 UTC, Lembrun commented
Yeah I know about the private marker, was just a brain fart