Pathlib /unit/mainwindow
qutebrowser/qutebrowser pull request #6254
Opened 2021-03-10 20:13 UTC by Lembrun

#176

2021-03-11 18:41 UTC, The-Compiler requested changes

2021-03-11 18:41 UTC, The-Compiler commented on tests/unit/mainwindow/test_prompt.py
> +            (testdir / directory).mkdir(exist_ok=True, parents=True)
Is the `exist_ok=True` needed here? We should get an empty `tmp_path` for every time this test runs, so I don't think it should ever exist?

2021-03-11 18:41 UTC, The-Compiler commented on tests/unit/mainwindow/test_prompt.py
> +            (testdir / directory).mkdir(exist_ok=True, parents=True)
Is the `exist_ok=True` needed here?

2021-03-11 18:46 UTC, Lembrun commented on tests/unit/mainwindow/test_prompt.py
> +            (testdir / directory).mkdir(exist_ok=True, parents=True)
You're indeed right

2021-03-12 21:05 UTC, merged

2021-03-12 21:05 UTC, The-Compiler commented
Thanks!