[wip] Add soft flag to keep pinned tabs in tab-only
qutebrowser/qutebrowser pull request #6287
Opened 2021-03-15 15:49 UTC by nichobi

Adds a `--soft` flag to `:tab-only`, which keeps pinned tabs without prompting the user. Essentially it's the opposite of `--force`.

This is my first pull request for qutebrowser, so I'd appreciate any feedback or guidance. So far this is a barebones implementation without any tests.

My use case is that I pin tabs precisely so they won't get closed by `:tab-only`, so it becomes somewhat annoying to have to decline the prompt each time.

2021-03-16 07:36 UTC, The-Compiler commented
That seems useful - I don't use pinned tabs myself at all, so I rely on users to tell me what's missing there :slightly_smiling_face: 

Let's first look at how the "API" of that command should look like to the user:

I guess with the `--soft` name, you got inspired by `--force`? I'd rather have a more descriptive name (say, `--keep-pinned` maybe?), even if `--force` also isn't very descriptive in this case.

Two more possibilities I can think of:

- Replacing `--force` entirely, with something like a `--pinned` flag, taking an argument like `close`, `ask` or `keep`.
- Using a setting instead of a flag instead - however, that's a bit less flexible, I think it makes more sense to keep it as a flag.

What do you think?

2021-03-16 12:46 UTC, nichobi commented
Yeah, I was a bit unsure what to call it, `keep-pinned` would be certainly be an improvement if keeping it as a flag. 
I lean towards your `--pinned`suggestion, since it seems more flexible, and would also clear up the combination of `--force --soft` which currently would just ignore the `--soft` flag.
If I was to implement this, should I attempt (temporary) compatibility with the `--force` flag, or is it okay to just replace it entirely, breaking people's bindings?

2021-03-17 10:28 UTC, The-Compiler commented
You can use something like `cmdutils.check_exclusive((force, soft), 'fs')` to make them mutually exclusive, similarly to what's already done for `--prev` and `--next` at the beginning of the function.

I'd still go for `--pinned` though - what we usually do for changes like this is to keep the old API around for a release, but with a deprecation warning. Something like (untested):

```python
if force:
    message.warning("--force is deprecated, use --pinned close instead.")
    pinned = 'close'
```

as well as a `@cmdutils.argument('force', hide=True)` decorator to hide it from the docs.

2021-03-18 12:20 UTC, nichobi commented
```python
    @cmdutils.register(instance='command-dispatcher', scope='window')
    @cmdutils.argument('pinned', choices=['prompt', 'close', 'keep'])
    @cmdutils.argument('force', hide=True)
    def tab_only(self, prev=False, next_=False, pinned='prompt', force=False):
```
I've changed the definition to the above, but `pinned` seems to be turned into a positional argument, i.e. `:tab-only close`. Is it not possible have it as a flag when it takes a string argument, i.e. `:tab-only --pinned close`?

2021-03-18 12:44 UTC, The-Compiler commented
That's because it's a positional argument in Python, but doesn't use a `False` default value (making it a flag).

You should be able to make the arguments explicitly [keyword only](https://python-3-for-scientists.readthedocs.io/en/latest/python3_advanced.html#keyword-only-arguments) by doing `self, *, prev=False, ...` and qutebrowser should do the right thing.

2021-03-18 14:44 UTC, The-Compiler requested changes
Thanks for the update! I think the only missing thing now is a test - search for `Pinned :tab-only` in `tests/end2end/features/tabs.feature` for some inspiration.

2021-03-18 14:44 UTC, The-Compiler commented on qutebrowser/browser/commands.py
> +            soft: Keep pinned tabs without prompting.
This can be removed now.

2021-03-18 15:30 UTC, nichobi commented on qutebrowser/browser/commands.py
> +            soft: Keep pinned tabs without prompting.
Oops! I've amended that commit

2021-03-18 17:34 UTC, The-Compiler requested changes

2021-03-18 17:34 UTC, The-Compiler commented on qutebrowser/browser/commands.py
>              self._tabbed_browser.tab_close_prompt_if_pinned(
In the lambda below this line (GitHub won't let me comment there as it's not part of your changes), `force=True` is still used, thus triggering the warning (and failing `test_pinned_tabonly_prompt_yes`). If you change that to `pinned='close'` instead, I think everything should work fine.

2021-03-23 13:27 UTC, merged

2021-03-23 13:27 UTC, The-Compiler commented
Looks great now, thanks! Pushed with some minimal changes to the docs in 103017876e3ad3a74591fdd5053addb11a43f8f5.

2021-03-23 13:31 UTC, nichobi commented
Thank you so much for all the help! It's made the codebase feel much less intimidating, so hopefully my next contribution will go smoother!