Pathlib /unit/utils
qutebrowser/qutebrowser pull request #6291
Opened 2021-03-16 21:14 UTC by Lembrun

#176 , haven't touched tests/unit/utils/test_urlutils as discussed in IRC

2021-03-18 18:22 UTC, The-Compiler commented
Looks like stuff [started failing](https://github.com/qutebrowser/qutebrowser/pull/6291/checks?check_run_id=2125739784) on Windows - I haven't taken a closer look yet, but it looks like some parts fail due to expecting `C:\Users\RUNNER~1\AppData\...` but getting `C:\Users\runneradmin\AppData\...`.

Gotta love Windows... I'll take a closer look once I feel like dealing with it.

2021-03-18 18:46 UTC, Lembrun commented on qutebrowser/utils/standarddir.py
> -    return os.path.abspath(os.path.join(args.basedir, suffix))
I've located the problem here, apparently pathlib.resolve doesn't behave the same way on windows for non existing path [https://stackoverflow.com/questions/42513056/how-to-get-absolute-path-of-a-pathlib-path-object](url) (though I haven't checked in a vm)

I'm going to eat but there are still some changes that I need to push for this one

2021-03-23 13:21 UTC, The-Compiler requested changes
I don't think the changes in `qutebrowser/utils/standarddir.py` make much sense (and they are also separate from the changes in the tests).

For `standarddir`, I'd rather switch over the `standarddir` functions entirely, rather than sprinkling `standarddir` and `str` conversions everywhere. But that will need some more planning (since it affects the entire codebase pretty much), so it really shouldn't be part of this PR I think.

2021-03-24 10:36 UTC, merged

2021-03-24 10:36 UTC, The-Compiler commented
Thanks! Merged with some more simplifications:

- 816ec60fe Remove changes to test_standarddir
- 27ceb8196 Simplify paths in test_jinja, _qtutils and _version