Hide long description of settings
qutebrowser/qutebrowser pull request #6999
Opened 2022-02-04 14:27 UTC by twigleingrid

Show only the first line of the description of a setting. 
This makes all the settings the same size, giving a better overview. 
Display or hide the description according to the button click.

2022-02-20 01:03 UTC, toofar reviewed
Can you talk more about what use cases you've considered that this change supports? I ask because I'm not completely sold on everything being the same size being more useful than have all the text available. Although I agree it looks better with all the rows the same size.

The motivation you've given is to "give a better overview". But I'm not sure the main use case of this page is to get an overview of settings. I assume people would be looking for a particular setting by either name, value or keyword. Maybe I am wrong but given the size of the page I would hope they were doing that by searching, not scrolling. So given that, this means that the set of searchable keywords on the page is now less, since the collapsed parts don't seem to show up when searching. Additionally, once you have found the setting you are looking for surely it is good to have all the instructions right there without having to click an extra button.

I don't work much with UIs though, nor do I use the settings page all that much. So I would be happy to hear other people's opinions.

2022-03-02 10:08 UTC, twigleingrid commented
Thank you for your review!
Giving the fact that the descriptions are of different sizes, it felt more chaotic for me. I thought the short descriptions, the first line, might give an overview and the user can decide if they need more information.  
I also think someone would rather search, but I figured the main keywords would appear in the setting name or in the first line of the description. Also sometimes some scrolling or scheming through the settings' names is still necessary, so the short version felt more pleasant to me.
But I am interested in other opinions as well!

2022-03-02 10:21 UTC, mschilli87 commented
IMHO if there is a setting that can only be found by a keyword 'hidden' in the long description, we should treat this as an issue with the short one not being clear enough. I like the new layout and would expect to find what I need. The extra click to get the details is a cost though, I agree. Not sure how to weigh this best. My feeling is this will require an executive decision (probably by @The-Compiler) in the end and we'll just go with it from there.

2022-03-02 14:01 UTC, The-Compiler commented
I don't really have a strong opinion on this, but I lean towards agreeing with @twigleingrid and @mschilli87.

As for the search, we might want to provide a more clever search for the page anyways - filtering all the displayed settings based on the searched term, and maybe even prioritizing the matches based on their relevance (matches on setting name > matches in first line of description > matches in full description).

It's even imaginable to special case `/` in qutebrowser to use that on-page search then - we might want to do something similar for e.g. PDFs displayed in the browser too, so it wouldn't be the only place something like that might be useful.

2022-03-02 14:11 UTC, The-Compiler requested changes
Something small I noticed while looking at the code.

I wonder though, wouldn't it be more appropriate to use [`<details>` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) for this? 

This would mean less re-inventing stuff in JS, and at least in Chromium, searching for the part inside the `<details>` also opens the element. For some reason this doesn't happen with qutebrowser/QtWebEngine though, but it still seems like a potentially simpler approach (at least if it's possible to style appropriately in CSS).

2022-03-02 14:11 UTC, The-Compiler commented on qutebrowser/html/settings.html
> +  let display = longDesc.style.display
Minor thing, but I suppose those could be using `const` instead of `let`?

2022-03-04 11:18 UTC, twigleingrid commented
Thank you for reviewing, @The-Compiler! That's a nice idea to use the `details` tag!

2022-03-05 07:20 UTC, toofar approved these changes
Looks okay to me. The cursor does what I expect now which is the main thing I cared about!

Although if we want to quibble on making things the same size; I think the original Show less/more thing done in JS looked better because it was 1) inline when collapsed and 2) didn't interrupt the text when expanded. Those could maaaybe be addressed by making the first line of the setting text the summary, but that might make it less obvious that you should click on them.

2022-03-14 06:11 UTC, toofar approved these changes
That looks really good!

Edit: I don't think the test failures are related, you can ignore them.

https://user-images.githubusercontent.com/7419144/158114571-8a6c489f-4664-44f5-83ec-eb7173f87d6c.mp4

2022-03-15 11:09 UTC, twigleingrid commented
Thank you @toofar for adding the little video! I forgot to include screenshots, will remember for next time :)

2022-03-17 06:12 UTC, merged

2022-03-17 06:15 UTC, toofar commented
Thanks @twigleingrid, it was good seeing the iterative improvement!