Add `completion.item_padding`
qutebrowser/qutebrowser pull request #7292
Opened 2022-07-02 12:12 UTC by evan-leigh

2022-07-02 12:37 UTC, The-Compiler requested changes
This just crashes qutebrowser outright. Please make sure you actually try your code and can confirm it works.

2022-07-02 12:37 UTC, The-Compiler commented on qutebrowser/completion/completionwidget.py
> +            padding-bottom: {{ completion.item_padding['bottom'] }}px;
```suggestion
            padding-top: {{ conf.completion.item_padding['top'] }}px;
            padding-left: {{ conf.completion.item_padding['left'] }}px;
            padding-right: {{ conf.completion.item_padding['right'] }}px;
            padding-bottom: {{ conf.completion.item_padding['bottom'] }}px;
```

2022-07-03 17:25 UTC, segf00lt commented on qutebrowser/config/configdata.yml
> +  type: Padding
`type` should be:
```
type:
  name: Dict
  keytype: String
  valtype:
    name: Int
    minval: 0
```

2022-07-03 17:49 UTC, segf00lt commented
For controling the padding values it might be better to use separate options instead of a Dict.
```
completion.item_padding.top:
  default: 1
  type:
    name: Int
    minval: 0
  desc: Top padding (in pixels) of items in the completion window.

completion.item_padding.bottom:
  default: 1
  type:
    name: Int
    minval: 0
  desc: Bottom padding (in pixels) of items in the completion window.

completion.item_padding.left:
  default: 0
  type:
    name: Int
    minval: 0
  desc: Left padding (in pixels) of items in the completion window.

completion.item_padding.right:
  default: 0
  type:
    name: Int
    minval: 0
  desc: Right padding (in pixels) of items in the completion window.
```

And the changes for the stylesheet in completionwidget.py:
```
        QTreeView:item {
            padding-top: {{ conf.completion.item_padding.top }}px;
            padding-bottom: {{ conf.completion.item_padding.bottom }}px;
            padding-left: {{ conf.completion.item_padding.left }}px;
            padding-right: {{ conf.completion.item_padding.right }}px;
        }
```

2022-07-03 18:11 UTC, The-Compiler commented
Why? We already have a `Padding` type we use elsewhere, so it seems to make sense to use it here too, no?

2022-07-03 19:46 UTC, segf00lt commented
Yeah that makes more sense. I was thinking it would be a setting the user would occasionally change at runtime, but just as a setting in the config file it does make more sense to use `Padding`.

2023-02-22 20:27 UTC, vereis commented
This looks like it hasn't had any updates in awhile, @The-Compiler would you be open to another shot at implementing this feature?

2023-03-12 14:23 UTC, The-Compiler commented
@vereis Sorry for the delay, I was taking a bit of a break from qutebrowser stuff. I *think* this one should actually be okay from a quick look, unless you see something that would be missing here.

Usually with older PRs it's really appreciated if someone helps picking things up and getting them updated, but here I think there is nothing left to do, except on my end of things. I'm currently focusing on Qt 6 stuff, but then want to go back and hopefully merge a big batch of PRs again after that.

2023-03-13 10:06 UTC, mschilli87 approved these changes
`configdata.yml` changes LGTM as well.

2023-03-13 10:49 UTC, vereis commented
No worries at all! I really appreciate it; I've only started using qutebrowser recently but I'm really loving it so far!

Really appreciate you following up again :heart: Looking forward to everything else you have in store!

2023-12-04 15:19 UTC, arza-zara approved these changes

2023-12-04 15:19 UTC, arza-zara commented on qutebrowser/config/configdata.yml
> +    right: 0
I somewhat prefer the old default of 0 for all

2024-01-02 21:46 UTC, closed without merging

2024-01-03 00:09 UTC, mschilli87 commented
@The-Compiler: Just making sure this doesn't slip through your attention due to @kyza0dev removing their fork.