Add Unicode normalization and IDNA encoding to qute-pass userscript
qutebrowser/qutebrowser pull request #8133
Opened 2024-03-18 15:43 UTC by DrTobe

I have implemented support for Internationalized Domain Names (IDNA). Currently, this only kicks in when the normal 'pass' mode (not 'gopass') is used because I am no gopass user so I could not test this right now.

@cryzed You are listed as script author, would you mind having a look at this?

2024-05-23 13:49 UTC, DrTobe commented
@The-Compiler Would you mind having a look at this?

2024-05-23 13:54 UTC, The-Compiler commented
I've never used either qute-pass or pass, so I can't say much. Maybe @bascht or @lufte have an opinion on this?

2024-05-23 15:30 UTC, cryzed commented
I don't use qutebrowser or qute-pass anymore, sorry.

2024-05-23 15:36 UTC, lufte commented
I can take a look later.

2024-05-23 21:45 UTC, lufte requested changes
So let me see if I get this right: the idea is to encode the domain of the requested URL, and encode all the domains stored in the pass store, to ensure we're comparing apples to apples. I think this makes sense.

I left some comments on stuff that's being computed over and over with no need.

2024-05-23 21:45 UTC, lufte commented on misc/userscripts/qute-pass
> +                idna_domain = idna_encode(domain)
This step should go outside the `for path, directories, file_names in os.walk(arguments.password_store, followlinks=True):` loop at line 152, as the domain doesn't change between entries in my password store.

2024-05-23 21:45 UTC, lufte commented on misc/userscripts/qute-pass
> +                idna_split_path = [idna_encode(part) for part in split_path]
And this one should go outside the `for secret in secrets` loop as the split_path doesn't change between different secrets under the same folder.

2024-05-23 22:20 UTC, DrTobe commented
> So let me see if I get this right: the idea is to encode the domain of the requested URL, and encode all the domains stored in the pass store, to ensure we're comparing apples to apples. I think this makes sense.

You got that right.

> I left some comments on stuff that's being computed over and over with no need.

I have moved these out of the loops to optimize that.

2024-05-24 22:31 UTC, lufte approved these changes
Looks great now :ok_hand:

2024-06-15 23:24 UTC, merged

2024-06-15 23:27 UTC, toofar commented
Thanks @DrTobe for the PR and @lufte for the reivew!