Rewrite `.feature` files to use the `"""` syntax
qutebrowser/qutebrowser pull request #8345
Opened 2024-10-15 13:22 UTC by mschilli87

fixes #8342

This is untested and purely based on the information provided in the referenced issue.
But it looked pretty straightforward to me so I just used a bit of `git grep` + `vim`-foo to insert the `"""` where I understood they would be required now, adjusting the indentation appropriately.

Let me know if I missed anything or messed up in any other way.

2024-10-15 13:38 UTC, The-Compiler requested changes

2024-10-15 13:40 UTC, The-Compiler commented on tests/end2end/features/backforward.feature
> +	    """
Huh, funny, GitHub shows it as indented in the comments view, but not in the "files changed" view. I think this is mixed indentation with `\t` plus four spaces now, which it certainly shouldn't be.

2024-10-15 13:51 UTC, mschilli87 commented on tests/end2end/features/backforward.feature
> +	    """
Yes, looks like my vim-settings messed that up. 😅 What indentation do you prefer? Should be an easy fix.

2024-10-15 13:53 UTC, The-Compiler commented on tests/end2end/features/backforward.feature
> +	    """
We mostly use four spaces in those files I believe. Could be that it's inconsistent unfortunately (I think some places there might use two spaces?).

2024-12-06 13:53 UTC, merged

2024-12-06 13:54 UTC, The-Compiler commented
Thanks for getting the ball rolling! Done with a couple of more changes:

- 629a38d65 Upgrade to pytest-bdd 8
- f52492621 Fix tab indentation in feature files
- bb462c260 pytest-bdd 8: Fix indentations
- cec00266d pytest-bdd 8: Fix tags
- a8a5068e6 pytest-bdd 8: Fix missing multiline step quoting
- f4260a6e5 pytest-bdd 8: Fix comments and remaining syntax issues
- f91dc2d52 pytest-bdd 8: Adjust Python code for multiline steps
- 59fd7876a pytest-bdd 8: Fix borked tag
- aed06c5f4 Add gherkin-official changelog URL
- e2fb1fba8 Revert "Bleeding requirements: Use pytest-bdd release"
- acc06cdd3 Merge branch 'gherkin8342'
- a7b566e7b Remove pytest-bdd<8 limit